name: Node CI/CD workflow

on: [push]

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker build
      run: |
        docker build . -t michieldebruyn/bs2-frontend:latest
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}

    - name: Docker push
      run: |
        docker push michieldebruyn/bs2-frontend
